# Generated by Django 5.2 on 2025-04-26 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productanalytic',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='products.product'),
        ),
        migrations.AddField(
            model_name='shopanalytic',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='productanalytic',
            unique_together={('product', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='shopanalytic',
            unique_together={('shop', 'date')},
        ),
    ]
